
// 样品字段名称
export const sampleFieldsName = {
  name: "样品名称",
  sn: "样品编号",
  specification: "规格型号",
  testPart: "检测部位",
  projectPartOrUse: "工程部位/用途",
  amount: "样品数量",
  behalfAmount: "代表数量",
  manufacturer: "生产厂家",
  batchNumber: "产品批号",
  productionDate: "出厂日期",
  productionSn: "出厂编号",
  enterSiteDate: "进场日期",
  maintainCondition: "养护条件",
  testItems: "检测参数",
  witnessUnit: "见证单位",
  witness: "见证人",
  witnessCertNo: "见证人证书号",
  samplingCompany: "取样单位",
  samplingPlace: "取样地点",
  samplingPerson: "取样人",
  samplingDate: "取样日期",
  samplingPersonNumber: "取样人证件号"
}

export const dataItemFieldsName = {
  isSubcontract: "是否外围报告",
  laboratoryId: "试验室ID",
  laboratory: "试验室名称",
  testLaboratory: "检测机构",
  consignSn: "委托编号",
  // sampleSn: "样品编号",
  // recordSn: "记录编号",
  sn: "报告编号",
  consignUnit: "委托单位",
  checkType: "委托类型",
  sampleSender: "委托人",
  sampleSenderTel: "委托人电话",
  project: "项目名称",
  projectSection: "标段名称",
  consignDate: "委托日期",
  qualification: "资质类型",
  testBasis: "检测依据",
  evaluationStandard: "判断依据",
  tester: "检测人",
  recorder: "记录人",
  assistant: "协助人",
  editor: "编写人",
  reviewer: "复核人",
  auditor: "审核人",
  approver: "批准人",
  equipmentSn: "设备编号",
  equipmentName: "设备名称",
  auditTime: "审核时间",
  testTimeBegin: "检测开时间",
  testTimeEnd: "检测结束时间",
  isQualified: "是否合格",
  signDate: "签发日期",
  isTemporary: "是否临时报告",
  securityCode: "防伪码值",
  queryCode: "查询码/验证码",
  verdictRemark: "备注",
  samples: "样品",
  attachments: "附件"
}