import type { ICustomizeValue } from './ICustomizeValue'

export interface IDeviceEntity {
  transferApplyNo: null
  laboratoryId: string
  accuracy: ''
  callOutType: null
  keeperId: ''
  type: '通用设备'
  transferApplyStatus: '00'
  archiveSn: '0801'
  coefficientElectronic: ''
  callOutUserName: null
  turnTime: null
  unitCode: 'gfzx'
  quoteEqId: null
  applyCallInUserName: null
  id: '46928081910b90a901910b9c49780090'
  callInUserName: null
  departName: '科技设备处'
  serveLocationId: '8a8ab0b246dc81120146dc8180ba0017'
  installRemark: null
  coefficientMachine: ''
  serveLocation: '蜀道投资集团有限责任公司'
  nextCheckDate: 1722643200000
  callOutUserId: null
  turnRemark: null
  callInId: null
  abnormal: null
  size: ''
  checkPeriod: 1
  repairServiceEndTime: null
  createName: '管理员'
  status: '正常'
  installFee: null
  updateDate: 1722928388000
  factoryPrice: null
  iotAuthUserCount: 0
  equipmentSn: '0801'
  installContact: null
  egressStatus: '40'
  file: []
  isDeleted: '0'
  callOutWay: null
  labRangeType: '不限'
  departId: '2c9284d5767eda4a01768438f1f4009e'
  power: ''
  createDate: 1722476677000
  testItem: null
  applyCallInId: null
  managerId: ''
  userId: ''
  checkUnit: ''
  rentStatus: '0'
  installUserId: null
  callInName: null
  isIot: '0'
  transferStart: null
  supplierTel: ''
  standard: ''
  transferStatus: '10'
  applyCallInUserId: null
  callInRemark: null
  preCheckResult: null
  sysCompanyCode: 'A03'
  managerName: ''
  callOutId: null
  isExtension: null
  checkCertificateSn: ''
  manageType: '检测仪器-固定资产'
  assetSn: ''
  managementWay: ''
  keeperName: ''
  applyCallInType: null
  callOutTime: null
  checkType: '比对'
  callInWay: null
  callInUserId: null
  unitName: '蜀道投资集团有限责任公司'
  netValue: ''
  checkPeriodUnit: '月'
  eqRange: ''
  callInTime: null
  updateName: '管理员'
  unit: null
  transferEnd: null
  name: '0801'
  sysOrgCode: null
  testManageSn: ''
  turnContact: null
  operationDate: null
  depreciationFee: null
  callInType: null
  installUser: null
  supplierId: null
  transportFee: null
  customizeValues: ICustomizeValue[]
  preCheckDate: 1720051200000
  installDescription: null
  buyDate: number
  orderNum: null
  storageSite: '重庆'
  remark: ''
  installTime: null
  callOutRemark: null
  applyCallInName: null
  parentEqId: null
  productionDate: null
  updateBy: 'admin'
  buyId: null
  transferApplyId: null
  supplierName: ''
  factory: ''
  quantity: null
  factorySn: ''
  callOutName: null
  coefficientHot: ''
  laboratoryName: null
  turnUser: null
  userName: ''
  transferRecordId: null
  rootEqId: null
  serveLocationType: '10'
  createBy: 'admin'
  isGlsy: '0'
  factorySupportTel: ''
}
