import { allFields, allInfo, allTypeCode } from './allFileds'

// eslint-disable-next-line no-unused-vars, unused-imports/no-unused-vars
const a = allFields // 节约时间

const collectionConfig = {
  1: {
    sjcc: '试件尺寸',
    sjqd: '设计强度',
    hjmj: '横截面积',
    lqi: '龄期',
    hzai1: '荷载1',
    hzai2: '荷载2',
    hzai3: '荷载3',
    qddbz: '强度代表值',
  },
  2: {
    sjcc: '试件尺寸',
    sjqd: '设计强度',
    hjmj: '横截面积',
    lqi: '龄期',
    hzai1: '荷载1',
    hzai2: '荷载2',
    hzai3: '荷载3',
    hzai4: '荷载4',
    hzai5: '荷载5',
    hzai6: '荷载6',
    qddbz: '强度代表值',
  },
  3: {
    sjcc: '试件尺寸',
    sjqd: '设计强度',
    hjmj: '横截面积',
    lqi: '龄期',
    hzai1: '荷载1',
    hzai2: '荷载2',
    hzai3: '荷载3',
    qddbz: '强度代表值',
  },
  4: {
    sjcc: '试件尺寸',
    sjqd: '设计强度',
    hjmj: '横截面积',
    lqi: '龄期',
    hzai1: '荷载1',
    hzai2: '荷载2',
    hzai3: '荷载3',
    hzai4: '荷载4',
    hzai5: '荷载5',
    hzai6: '荷载6',
    qddbz: '强度代表值',
  },
  5: {
    sjcc: '试件尺寸',
    sjqd: '设计强度',
    hjmj: '横截面积',
    lqi: '龄期',
    hzai1: '荷载1',
    hzai2: '荷载2',
    hzai3: '荷载3',
    hzai4: '荷载4',
    hzai5: '荷载5',
    hzai6: '荷载6',
    qddbz: '强度代表值',
  },
  6: {
    sjcc: '试件尺寸',
    sjqd: '设计强度',
    hjmj: '横截面积',
    lqi: '龄期',
    hzai1: '荷载1',
    hzai2: '荷载2',
    hzai3: '荷载3',
    qddbz: '强度代表值',
  },
  7: {
    sjcc: '试件尺寸',
    sjqd: '设计强度',
    hjmj: '横截面积',
    lqi: '龄期',
    hzai1: '荷载1',
    hzai2: '荷载2',
    hzai3: '荷载3',
    qddbz: '强度代表值',
  },
  8: {
    sjcc: '试件尺寸',
    sjqd: '设计强度',
    hjmj: '横截面积',
    lqi: '龄期',
    hzai1: '荷载1',
    hzai2: '荷载2',
    hzai3: '荷载3',
    qddbz: '强度代表值',
  },
  9: {
    sjcc: '试件尺寸',
    sjqd: '设计强度',
    hjmj: '横截面积',
    lqi: '龄期',
    hzai1: '荷载1',
    hzai2: '荷载2',
    hzai3: '荷载3',
    qddbz: '强度代表值',
  },
  10: {
    sjcc: '试件尺寸',
    sjqd: '设计强度',
    hjmj: '横截面积',
    lqi: '龄期',
    hzai1: '荷载1',
    hzai2: '荷载2',
    hzai3: '荷载3',
    qddbz: '强度代表值',
  },
  11: {},
  12: {
    sjcc: '试件尺寸',
    sjqd: '设计强度',
    hjmj: '横截面积',
    lqi: '龄期',
    hzai1: '荷载1',
    hzai2: '荷载2',
    hzai3: '荷载3',
    qddbz: '强度代表值',
  },
  13: {
    hjmj: '横截面积',
    kd: '宽度',
    hd: '厚度',
    xz: '形状',
    hzai1: '荷载1',
    hzai2: '荷载2',
    hzai3: '荷载3',
    hzai4: '荷载4',
    hzai5: '荷载5',
    hzai6: '荷载6',
    ph: '牌号',
    gczj: '公称直径',
    ggxh: '规格型号',
    klqd1: '抗拉强度1',
    klqd2: '抗拉强度2',
    klqd3: '抗拉强度3',
    klqd4: '抗拉强度4',
    klqd5: '抗拉强度5',
    klqd6: '抗拉强度6',
    sqfl1: '上屈服力1',
    sqfl2: '上屈服力2',
    sqfl3: '上屈服力3',
    sqfl4: '上屈服力4',
    sqfl5: '上屈服力5',
    sqfl6: '上屈服力6',
    xqfl1: '下屈服力1',
    xqfl2: '下屈服力2',
    xqfl3: '下屈服力3',
    xqfl4: '下屈服力4',
    xqfl5: '下屈服力5',
    xqfl6: '下屈服力6',
    sqfqd1: '上屈服强度1',
    sqfqd2: '上屈服强度2',
    sqfqd3: '上屈服强度3',
    sqfqd4: '上屈服强度4',
    sqfqd5: '上屈服强度5',
    sqfqd6: '上屈服强度6',
    xqfqd1: '下屈服强度1',
    xqfqd2: '下屈服强度2',
    xqfqd3: '下屈服强度3',
    xqfqd4: '下屈服强度4',
    xqfqd5: '下屈服强度5',
    xqfqd6: '下屈服强度6',
  },
  14: {
    hjmj: '横截面积',
    hzai1: '荷载1',
    hzai2: '荷载2',
    hzai3: '荷载3',
    hzai4: '荷载4',
    hzai5: '荷载5',
    hzai6: '荷载6',
    ph: '牌号',
    gczj: '公称直径',
    ggxh: '规格型号',
    klqd1: '抗拉强度1',
    klqd2: '抗拉强度2',
    klqd3: '抗拉强度3',
    klqd4: '抗拉强度4',
    klqd5: '抗拉强度5',
    klqd6: '抗拉强度6',
  },
  15: {
    hjmj: '横截面积',
    hzai1: '荷载1',
    hzai2: '荷载2',
    hzai3: '荷载3',
    hzai4: '荷载4',
    hzai5: '荷载5',
    hzai6: '荷载6',
    ph: '牌号',
    gczj: '公称直径',
    ggxh: '规格型号',
    klqd1: '抗拉强度1',
    klqd2: '抗拉强度2',
    klqd3: '抗拉强度3',
    klqd4: '抗拉强度4',
    klqd5: '抗拉强度5',
    klqd6: '抗拉强度6',
  },
  16: {
    hzai1: '荷载1',
    hzai2: '荷载2',
    hzai3: '荷载3',
    hzai4: '荷载4',
    hzai5: '荷载5',
    hzai6: '荷载6',
    txml1: '弹性模量1',
    txml2: '弹性模量2',
    txml3: '弹性模量3',
    txml4: '弹性模量4',
    txml5: '弹性模量5',
    txml6: '弹性模量6',
  },
  17: {
    sjcc: '试件尺寸',
    sjqd: '设计强度',
    hjmj: '横截面积',
    hzai1: '荷载1',
    hzai2: '荷载2',
    hzai3: '荷载3',
    hzai4: '荷载4',
    hzai5: '荷载5',
    hzai6: '荷载6',
    qddbz: '强度代表值',
  },
}

// 换种方法提高效率
const cKeys = Object.keys(allInfo)
// eslint-disable-next-line array-callback-return
cKeys.map((key) => {
  const obj = {}
  // eslint-disable-next-line array-callback-return
  allInfo[key].split(',').map((filed) => {
    obj[allFields[filed]] = filed
  })
  collectionConfig[allTypeCode[key]] = obj
})

export { collectionConfig }
