export const mockData = {
  equipmentName: '数字万用表',
  factorySn: 'SN202309001',
  specifications: 'MODEL-X200',
  certName: '校准证书',
  certSn: 'CAL-2023-09876',
  certType: 'calibrate',
  checkUnit: '国家计量院',
  checkTime: '2023-09-15',
  validityDate: '2024-09-14',
  checkBasis: 'JJG 123-2018 数字万用表检定规程',
  checkVerdict: '合格',
  checkRemark: '环境温度23℃±1℃，湿度60%RH',
  checkItemList: [
    {
      checkItemName: '直流电压测量',
      checkBasis: 'JJG 123-2018 数字万用表检定规程, 第5.2条款',
      checkRequirements: '量程2V，分辨率0.001V',
      checkResult: '±0.02V',
      confirmResult: '合格',
      remark: '两次测量平均值',
      processInfos: [
        {
          processItemName: '零点校准',
          processResult: '0.000V',
          processBasis: '附录A',
          processRequirements: '偏差≤±0.005V',
          deviationAllowed: '±0.005V',
          processMaxDeviation: '+0.003V',
          processVerdict: '合格',
        },
        {
          processItemName: '量程校准',
          processResult: '1.999V',
          processBasis: '附录B',
          processRequirements: '偏差≤±0.01%',
          deviationAllowed: '±0.002V',
          processMaxDeviation: '-0.001V',
          processVerdict: '合格',
        },
      ],
    },
    {
      checkItemName: '交流电流测量',
      checkBasis: '第5.5条款',
      checkRequirements: '量程10A，频率50Hz',
      checkResult: '合格',
      confirmResult: '合格',
      remark: '负载测试通过',
      processInfos: [
        {
          processItemName: '波形失真测试',
          processResult: 'THD＜1%',
          processBasis: '附录C',
          processRequirements: 'THD≤3%',
          deviationAllowed: '3%',
          processMaxDeviation: '0.8%',
          processVerdict: '合格',
        },
      ],
    },
  ],
}
