/** 委托模块字段名称映射 */
export const consignMapper = {
  consignBigType: '委托类型',
  consignType: '检测类型',
  qualificationTypeId: '资质类型',
  testType: '检测形式',
  snTypeId: '编号类型',
  consignCode: '委托编号',
  checkTypeId: '检测类别',
  sampleSource: '样品来源',
  consignUnitName: '委托单位',
  projectTenderName: '工程项目',
  sampleSender: '委托人',
  unitProjectName: '单位工程',
  consignDate: '委托日期',
  preConsignCode: '预委托编号',
  postFormId: '邮寄信息',
  reportHandOverType: '报告发放方式',
  buildUnitName: '建设单位',
  buildWitness: '建设单位见证人',
  buildWitnessLicenseNumber: '建设单位见证人证件号',
  buildWitnessPhone: '建设单位见证人电话',
  witnessUnitName: '监理单位',
  witness: '监理单位见证人',
  witnessLicenseNumber: '监理单位见证人证件号',
  witnessPhone: '监理单位见证人电话',
  paymentUnitName: '缴费单位',
  extractSampleUnit: '抽样单位',
  sampleSendUnitName: '送样单位',
  extractSamplePerson: '抽样人',
  extractSamplePersonTel: '抽样人电话',
}

/** 样品模块字段名称映射 */
export const objectMapper = {
  testObjectCode: '样品编号',
  bigCategoryId: '大类',
  testSampleLevelName: '样品层次',
  testSampleDisplayName: '样品名称',
  standard: '规格型号',
  model: '型号',
  specification: '规格',
  label: '标号',
  grade: '等级',
  projectPartAndUse: '工程部位/用途',
  subProject: '分项工程',
  unitProject: '单位工程',
  part: '检测部位',
  status: '样品状态',
  description: '样品描述',
  remark: '备注',
  testVerdictRemark: '结论备注',
  samplingDate: '取样时间',
  samplingPlace: '取样地点',
  samplingCompany: '取样单位',
  samplingPerson: '取样人',
  samplingPersonNumber: '取样人证件号',
  samplingInfo: '抽样信息',
  testVerdict: '检验结论',
  isQualified: '是否合格',
  delegatesNum: '代表数量',
  sampleNum: '样品数量',
  level: '样品层级',
  testStartDate: '试验开始日期',
  testEndDate: '试验结束日期',
  testConditions: '试验环境条件',
  sampleProcessMethod: '测后样品处理',
  sampleAmount: '计价数量',
  isRetentionSample: '是否留样',
  retentionHowLong: '留样时长',
  taskAssignType: '任务分配类型',
  taskAssignDate: '任务分配时间',
  isNeedConclusion: '是否需要检测结论',
  baseStandardProvider: '规程提供方',
}
