/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'home': RouteRecordInfo<'home', '/', Record<never, never>, Record<never, never>>,
    '404': RouteRecordInfo<'404', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    'account-book': RouteRecordInfo<'account-book', '/account-book', Record<never, never>, Record<never, never>>,
    'account-book-detail': RouteRecordInfo<'account-book-detail', '/account-book/detail', Record<never, never>, Record<never, never>>,
    'appointment-management': RouteRecordInfo<'appointment-management', '/appointment-management', Record<never, never>, Record<never, never>>,
    'addOrEditPreTask': RouteRecordInfo<'addOrEditPreTask', '/appointment-management/add', Record<never, never>, Record<never, never>>,
    '/appointment-management/innerForm': RouteRecordInfo<'/appointment-management/innerForm', '/appointment-management/innerForm', Record<never, never>, Record<never, never>>,
    'audit': RouteRecordInfo<'audit', '/audit', Record<never, never>, Record<never, never>>,
    'audit-handle': RouteRecordInfo<'audit-handle', '/audit/handle', Record<never, never>, Record<never, never>>,
    'device': RouteRecordInfo<'device', '/device', Record<never, never>, Record<never, never>>,
    'Incubator': RouteRecordInfo<'Incubator', '/incubator', Record<never, never>, Record<never, never>>,
    'IncubatorDetail': RouteRecordInfo<'IncubatorDetail', '/incubator/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'ledger-proc': RouteRecordInfo<'ledger-proc', '/ledger-proc', Record<never, never>, Record<never, never>>,
    'abnormal-detail': RouteRecordInfo<'abnormal-detail', '/ledger-proc/detail', Record<never, never>, Record<never, never>>,
    'ledger-proc-edit': RouteRecordInfo<'ledger-proc-edit', '/ledger-proc/edit', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'message': RouteRecordInfo<'message', '/message', Record<never, never>, Record<never, never>>,
    'message-detail': RouteRecordInfo<'message-detail', '/message/detail', Record<never, never>, Record<never, never>>,
    'preTask': RouteRecordInfo<'preTask', '/preTask', Record<never, never>, Record<never, never>>,
    'profile': RouteRecordInfo<'profile', '/profile', Record<never, never>, Record<never, never>>,
    'about-us': RouteRecordInfo<'about-us', '/profile/about-us', Record<never, never>, Record<never, never>>,
    'password': RouteRecordInfo<'password', '/profile/password', Record<never, never>, Record<never, never>>,
    'room': RouteRecordInfo<'room', '/room', Record<never, never>, Record<never, never>>,
    'record': RouteRecordInfo<'record', '/room/record', Record<never, never>, Record<never, never>>,
    'addSampleSendTask': RouteRecordInfo<'addSampleSendTask', '/sample-send', Record<never, never>, Record<never, never>>,
    '/sample-send/sendForm': RouteRecordInfo<'/sample-send/sendForm', '/sample-send/sendForm', Record<never, never>, Record<never, never>>,
    'timedTask': RouteRecordInfo<'timedTask', '/timedTask', Record<never, never>, Record<never, never>>,
    'addOrEditTimedTask': RouteRecordInfo<'addOrEditTimedTask', '/timedTask/add', Record<never, never>, Record<never, never>>,
  }
}
